// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANvWHrfjeD4AIsL9YD2EBOIWACLNx2GRo',
    appId: '1:920047912475:web:99b6ddfd9da2c2b4ce9abe',
    messagingSenderId: '920047912475',
    projectId: 'mimang-a0652',
    authDomain: 'mimang-a0652.firebaseapp.com',
    storageBucket: 'mimang-a0652.appspot.com',
    measurementId: 'G-RX6STKVVK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJQOUSywAMUgAdN5eyX29egrOnysNUnU0',
    appId: '1:920047912475:android:2fc268e68a4cfa47ce9abe',
    messagingSenderId: '920047912475',
    projectId: 'mimang-a0652',
    storageBucket: 'mimang-a0652.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_tOHrapHyvhfGRSCoBrVT-LjUr91oO7Y',
    appId: '1:920047912475:ios:a5ae7608485bd53ace9abe',
    messagingSenderId: '920047912475',
    projectId: 'mimang-a0652',
    storageBucket: 'mimang-a0652.appspot.com',
    iosClientId: '920047912475-4stgv2n0g12ke0bghsrihcpj48nhj5qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.miMang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_tOHrapHyvhfGRSCoBrVT-LjUr91oO7Y',
    appId: '1:920047912475:ios:a5ae7608485bd53ace9abe',
    messagingSenderId: '920047912475',
    projectId: 'mimang-a0652',
    storageBucket: 'mimang-a0652.appspot.com',
    iosClientId: '920047912475-4stgv2n0g12ke0bghsrihcpj48nhj5qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.miMang',
  );
}
